---
  - name: Run simple hello world
    hosts: "localhost"
    become: true
    tasks:

      - name: Log app
        shell: 'pwd'
        register: app_output

      - debug:
          var: app_output.stdout_lines

      - name: Find txt files
        find:
          paths: ../src/envs
          file_type: file
          recurse: Yes
          patterns: "file_*.txt"
        register: files_matched

      - name: Debug files_matched
        debug:
          var: files_matched.files