---
  - name: Run simple hello world
    hosts: "localhost"
    become: true
    tasks:

      - name: Log app
        shell: 'pwd'
        register: app_output

      - debug:
          var: app_output.stdout_lines

      - name: Find txt files
        find:
          paths: ../src/envs
          patterns: "file_*.txt"
        register: files_matched

      - name: Debug files_matched
        debug:
          var: files_matched.files

      - name: Debug files_matched loop
        shell: 'cat pwd > test_file.txt'  
        register: echou_output
        loop: "{{ files_matched.files|flatten(levels=1) }}"
        loop_control:
          label: "{{ item.path }}"

      - debug:
          var: echou_output.stdout_lines