---
  - name: Run simple hello world
    hosts: "localhost"
    become: true
    tasks:

      - name: Find txt files
        ansible.builtin.find:
          paths: ../src/envs
          patterns: "file_*.txt"
        register: files_matched

      - name: Debug files_matched
        debug:
          var: files_matched

      - name: Debug files_matched loop
        shell: 'echo hi > {{item.path}}'  
        loop: "{{ files_matched.files|flatten(levels=1) }}"
        loop_control:
          label: "{{ item.path }}"

