---
  - name: Run simple hello world
    hosts: "localhost"
    become: true
    tasks:

      - name: Find txt files
        ansible.builtin.find:
          paths: ../src/envs
          patterns: "file_*.txt"
        register: files_matched

      - name: Debug files_matched
        debug:
          var: files_matched

      #- name: Debug files_matched loop
       # shell: 'echo hi > {{item.path}}'  
        #loop: "{{ files_matched.files|flatten(levels=1) }}"
        #loop_control:
         # label: "{{ item.path }}"

      - name: install virtualenv
        shell: 'pip3 install virtualenv'
      - name: install virtualenvwrapper
        shell: 'pip3 install virtualenvwrapper'
      - name: open bashrc
        shell: 'vim .bashrc'

      - name: set VIRTUALENVWRAPPER_PYTHON
        shell: 'export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3'
      - name: set WORKON_HOME=$HOME
        shell: 'export WORKON_HOME=$HOME/.virtualenvs'
      - name: set VIRTUALENVWRAPPER_VIRTUALENV
        shell: 'export VIRTUALENVWRAPPER_VIRTUALENV=/home/your_username/.local/bin/virtualenv'
      - name: set source
        shell: 'source ~/.local/bin/virtualenvwrapper.sh'

      - name: Creating Virtual Environments
        shell: 'python3 -m venv ../python-venv/{{ item.path | basename }}'  
        loop: "{{ query('sequence', 'start=1 end='+(files_matched.matched)|string) }}"

      - name: list venv
        shell: 'lsvirtualenv'

