---
  - name: Run simple hello world
    hosts: "localhost"
    become: true
    tasks:

      # - name: Debug files_matched loop 
      #   shell: 'basename -s .txt {{ item.path }}'
      #   loop: "{{ files_matched.files }}"
      #   loop_control:
      #    label: "{{ item.path }}"
      #   register: files_req

      # - name: files_req aff
      #   debug:
      #     var: files_req

      # - name: Apdate the apt
      #   shell: 'sudo apt-get update'

      # - name: "Check if path exists"
      #   stat:
      #     path: "/usr/local/bin/docker-compose"
      #   register: pip_existance

      # - name: Install pip
      #   shell: 'sudo apt install python3-pip'
      #   when: not pip_existance.stat.exists

      # - name: install virtualenv
      #   shell: 'pip install virtualenv'
      # - name: install virtualenvwrapper
      #   shell: 'pip install virtualenvwrapper'

      - name: Find txt files
        ansible.builtin.find:
          paths: ../src/envs
          patterns: "file-*.txt"
        register: files_matched

      - name: ensure file exists
        copy:
          content: ""
          dest: ~/.bashrc
          force: no
          group: sys
          owner: root
          mode: 0555

      - name: set VIRTUALENVWRAPPER_PYTHON
        lineinfile:
          path: ~/.bashrc
          line: 'export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3'

      - name: set WORKON_HOME=$HOME
        lineinfile:
          path: ~/.bashrc
          line: 'export WORKON_HOME=$HOME/.virtualenvs'

      - name: Set VIRTUALENVWRAPPER_VIRTUALENV
        lineinfile:
          path: ~/.bashrc
          line: 'export VIRTUALENVWRAPPER_VIRTUALENV=.~/.local/bin/virtualenv'

      - name: Set source
        lineinfile:
          path: ~/.bashrc
          line: 'source ~/.local/bin/virtualenvwrapper.sh'

      - name: Creating Virtual Environments 
        shell: "python3 -m venv ../python-venv/{{ item.path | basename | split('.') | first}}"  
        with_items: "{{ files_matched.files }}"

      - name: found directories
        find:
          paths: ../python-venv
          recurse: no
          file_type: directory
        register: found_directories

      - name: Activating Virtual Environments 
        shell: source ../python-venv/{{ item.path | basename }}/bin/activate 
        with_items: "{{ found_directories.files }}"
        args:
           executable: /bin/bash
